### ISSUE TITLE
Enhancement suggestion: CSS sprites

### ISSUE THREAD

**Issue by meulie** [Koken-Community-Support/OxyGen3#2]
![image](https://cloud.githubusercontent.com/assets/252923/14554238/d8c6e324-02eb-11e6-82d8-d8a3c22f0f0a.png)

I have no idea whether it is doable/easy/worth the effort, but it's being suggested as an improvement by GTmetrix  :)

**Comment by BlackSkorpio** [comment]
The footer icons is where it would be possible/worth making them one big img: but I'm not sure it's worth the "hazzle" and that the one image would become bigger then the separate small icons...

**Comment by BlackSkorpio** [comment]
Will incorporate this in a coming release...

**Comment by BlackSkorpio** [comment]
In 3.0.6
[UPDATED] Combined all the social footer icons in to one sprite cutting down the total number of request sent to the server with 26!.
